spring:
  application:
    name: twitter
  datasource:
    url: jdbc:postgresql://${TWITTER_POSTGRES_HOST}:${TWITTER_POSTGRES_DB_PORT}/${TWITTER_POSTGRES_DB_NAME}
    username: ${TWITTER_POSTGRES_USERNAME}
    password: ${TWITTER_POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC